name: homesforyou
favicon: null
layout_spectrum: 0.8102803917136043
typography_spectrum: 0.39310443843714893
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7604629492852837
  lightness: 0.06258886656723917
  saturation: 0.4597984009888023
  rhythmicContrast: 0.08665379416197538
purpose: []
